<a href="https://colab.research.google.com/github/Andrewseltzer/StatisticsHomework/blob/main/AndrewSeltzer_Homework_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


# for i in range(number)


# print(i)

In [3]:
for i in range(5,8):
  print(i)

5
6
7


# to find the numbers 5-8 then you write print(i) to get numbers

# need : at the end to apply range

In [4]:
for i in range(3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


# for i in range (3) means there will be 3 numbers and wants it to print Test Numbers as different numbers

In [5]:
def square(x):
  return x**2

In [6]:
square(5)

25

In [7]:
square(6)

36

In [8]:
square(123456)

15241383936

In [9]:
square(square(5))

625

In [10]:
square(square(square(2)))

256

In [11]:
def add_two(x):
  return x+2

In [12]:
add_two(5)

7

In [13]:
square(add_two(5))

49

In [14]:
choice="apple"

# have to put quotations around apple to have everything work the right way

In [15]:
if choice == "apple":

  print("You choose apples.")

else:

    print("You did not choose apples.")

You choose apples.


# need to have both options in quotations "if you choose apples" or "if you did not choose apples" both having print before quotations 

In [16]:
if choice == "apples":

  print("You choose apples.")
 

elif choice == "oramge":

  print("You choose oranges.")

else:

    print("You did not choose apples or oranges")

You did not choose apples or oranges


# is elif a typo or is that a different function?

In [17]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


# how do you make it where you type in the answer? is that by adding (i.e. apple):")?

In [19]:
import numpy as np

In [20]:
np.random.permutation(52)

array([50, 42, 23, 21, 12, 17, 26, 32, 51, 48,  2, 24, 13,  8, 34, 36, 10,
        1, 25, 47, 41, 35,  5, 33, 16,  7, 19,  3, 11, 37, 22,  6, 20, 49,
       15, 29, 38,  0,  9, 39, 14, 43, 45, 44, 30,  4, 28, 40, 27, 46, 18,
       31])

# you do np.random.permutation(52) becasue there are 52 cards in a deck

In [21]:
card= np.random.permutation(52)

#you get the different cards by writing card

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [22]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [23]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [24]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# confused what these 3 steps do and how it related to the deck of cards, is it telling the percent of getting a 4, or 13?

In [25]:
suits = ['Clubs','spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

# this is important because its identifying the different suits and names of the cards

In [27]:
suits

['Clubs', 'spades', 'Hearts', 'Diamonds']

In [28]:
suits[0]

'Clubs'

In [29]:
names[1]

'Two'

In [30]:
def card_name(card_number):

  suit = card_number//13
  name = card_number%13

  return names[name] + " of" + suits[suit]

In [31]:
card_name(0)

'Ace ofClubs'

In [32]:
card_name(5)

'Six ofClubs'

In [33]:
card_name(1)

'Two ofClubs'

In [34]:
card_name(2)

'Three ofClubs'

In [35]:
card_name(51)

'King ofDiamonds'

In [36]:
card_name(13)

'Ace ofspades'

In [37]:
cards = np.random.permutation(52)

In [38]:
top_of_deck       =card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck  = card_name(cards[-1])

In [39]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Eight ofDiamonds', 'Jack ofHearts', 'Nine ofDiamonds')

In [40]:
for i in range(5):
    print(card_name(cards[i]))

Eight ofDiamonds
Jack ofHearts
Four ofspades
Jack ofDiamonds
Five ofClubs


In [41]:
for i in range(15):
    print(card_name(cards[i]))

Eight ofDiamonds
Jack ofHearts
Four ofspades
Jack ofDiamonds
Five ofClubs
King ofDiamonds
Seven ofHearts
Ten ofClubs
Three ofDiamonds
Six ofDiamonds
Seven ofClubs
Queen ofClubs
Ten ofDiamonds
Four ofClubs
Jack ofClubs


In [42]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [43]:
suits = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [44]:
i = np.random.randint(4)
j = np.random.randint(13)

In [45]:
i,j

(1, 11)

In [46]:
suits[i]

'p'

In [47]:
card[j]

'q'

In [48]:
from IPython.core.display import display, HTML

In [49]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [50]:
img = card_url_head + suits[i] + card[j] + card_url_tail

In [51]:
show_img(img)

In [52]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suits[i]+card[j]

In [53]:
card_image(3)

'k4'

In [54]:
img = card_url_head + card_image(3) + card_url_tail

In [55]:
show_img(img)

In [56]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)