<a href="https://colab.research.google.com/github/Andrewseltzer/Andrewseltzer/blob/main/Seltzer_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
  print(i)

5
6
7


In [3]:
for i in range(3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [4]:
def square(x):
  return x**2

In [5]:
square(5)

25

In [7]:
square(6)

36

In [8]:
square(123456)

15241383936

In [9]:
square(square(5))

625

In [10]:
square(square(square(2)))

256

In [12]:
def add_two(x):
  return x+2

In [13]:
add_two(5)

7

In [14]:
square(add_two(5))

49

In [15]:
choice="apple"

In [20]:
if choice == "apple":

  print("You choose apples.")

else:

    print("You did not choose apples.")

You choose apples.


In [21]:
if choice == "apples":

  print("You choose apples.")
 

elif choice == "oramge":

  print("You choose oranges.")

else:

    print("You did not choose apples or oranges")

You did not choose apples or oranges


In [22]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): pear


In [26]:
import numpy as np

In [28]:
np.random.permutation(52)

array([42, 20,  2, 31, 40, 50, 23, 26,  4, 36, 37, 14, 10,  1,  3, 28, 16,
       35, 25, 21, 24, 27, 13, 47,  9, 41,  6, 49, 45, 48, 51, 32, 39, 19,
       44, 30,  5, 29, 17,  8, 46, 33, 38, 12, 22,  7, 15, 34, 18, 11,  0,
       43])

In [31]:
card= np.random.permutation(52)

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [35]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [36]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [37]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [38]:
suits = ['Clubs','spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [39]:
suits

['Clubs', 'spades', 'Hearts', 'Diamonds']

In [40]:
suits[0]

'Clubs'

In [41]:
names[1]

'Two'

In [42]:
def card_name(card_number):

  suit = card_number//13
  name = card_number%13

  return names[name] + " of" + suits[suit]

In [44]:
card_name(0)

'Ace ofClubs'

In [45]:
card_name(1)

'Two ofClubs'

In [46]:
card_name(2)

'Three ofClubs'

In [47]:
card_name(51)

'King ofDiamonds'

In [48]:
card_name(13)

'Ace ofspades'

In [49]:
cards = np.random.permutation(52)

In [50]:
top_of_deck       =card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck  = card_name(cards[-1])

In [52]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Seven ofClubs', 'Four ofHearts', 'Five ofspades')

In [53]:
for i in range(5):
    print(card_name(cards[i]))

Seven ofClubs
Four ofHearts
King ofDiamonds
King ofHearts
Four ofClubs


In [54]:
for i in range(15):
    print(card_name(cards[i]))

Seven ofClubs
Four ofHearts
King ofDiamonds
King ofHearts
Four ofClubs
Seven ofHearts
Two ofClubs
Nine ofClubs
Ace ofHearts
Eight ofClubs
Seven ofspades
Jack ofClubs
Three ofspades
Ten ofDiamonds
Four ofspades


In [55]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [56]:
suits = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [59]:
i = np.random.randint(4)
j = np.random.randint(13)

In [60]:
i,j

(0, 6)

In [64]:
from IPython.core.display import display, HTML

In [65]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [68]:
img = card_url_head + suit[i] + card[j] + card_url_tail

NameError: ignored

In [69]:
show_img(img)

NameError: ignored