<a href="https://colab.research.google.com/github/Andrewseltzer/StatisticsHomework/blob/main/Seltzer_Lab_3.(Homework)ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
for i in range(5,8):
  print(i)

5
6
7


In [8]:
for i in range(3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [9]:
def square(x):
  return x**2

In [10]:
square(5)

25

In [11]:
square(6)

36

In [12]:
square(123456)

15241383936

In [13]:
square(square(5))

625

In [14]:
square(square(square(2)))

256

In [15]:
def add_two(x):
  return x+2

In [16]:
add_two(5)

7

In [17]:
square(add_two(5))

49

In [18]:
choice="apple"

In [19]:
if choice == "apple":

  print("You choose apples.")

else:

    print("You did not choose apples.")

You choose apples.


In [20]:
if choice == "apples":

  print("You choose apples.")
 

elif choice == "oramge":

  print("You choose oranges.")

else:

    print("You did not choose apples or oranges")

You did not choose apples or oranges


In [22]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [23]:
import numpy as np

In [24]:
np.random.permutation(52)

array([24, 40,  1, 49,  3, 45, 31, 18,  9, 27, 11, 43, 47, 15, 29, 26, 38,
        5, 21, 51, 34, 13,  4, 44, 25, 32,  7, 46, 37, 39, 35,  2, 12,  8,
       30, 17,  6, 28, 48, 10, 33,  0, 16, 41, 19, 50, 22, 20, 23, 42, 36,
       14])

In [25]:
card= np.random.permutation(52)

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [26]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [27]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [28]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [29]:
suits = ['Clubs','spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [30]:
suits

['Clubs', 'spades', 'Hearts', 'Diamonds']

In [31]:
suits[0]

'Clubs'

In [32]:
names[1]

'Two'

In [33]:
def card_name(card_number):

  suit = card_number//13
  name = card_number%13

  return names[name] + " of" + suits[suit]

In [34]:
card_name(0)

'Ace ofClubs'

In [35]:
card_name(1)

'Two ofClubs'

In [36]:
card_name(2)

'Three ofClubs'

In [37]:
card_name(51)

'King ofDiamonds'

In [38]:
card_name(13)

'Ace ofspades'

In [39]:
cards = np.random.permutation(52)

In [40]:
top_of_deck       =card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck  = card_name(cards[-1])

In [41]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Queen ofspades', 'Three ofspades', 'Two ofspades')

In [42]:
for i in range(5):
    print(card_name(cards[i]))

Queen ofspades
Three ofspades
Eight ofClubs
King ofHearts
Jack ofHearts


In [43]:
for i in range(15):
    print(card_name(cards[i]))

Queen ofspades
Three ofspades
Eight ofClubs
King ofHearts
Jack ofHearts
King ofspades
Three ofHearts
Five ofDiamonds
Ace ofDiamonds
Six ofClubs
Three ofClubs
Five ofHearts
Jack ofspades
Three ofDiamonds
Eight ofspades


In [44]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [45]:
suits = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [46]:
i = np.random.randint(4)
j = np.random.randint(13)

In [47]:
i,j

(1, 0)

In [54]:
suits[i]

'p'

In [55]:
card[j]

'a'

In [56]:
from IPython.core.display import display, HTML

In [57]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [60]:
img = card_url_head + suits[i] + card[j] + card_url_tail

In [62]:
show_img(img)

In [75]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suits[i]+card[j]

In [76]:
card_image(3)

'k4'

In [77]:
img = card_url_head + card_image(3) + card_url_tail

In [78]:
show_img(img)

In [79]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)